name: Lint
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: sudo apt-get install shellcheck
      - run: shellcheck --exclude=SC2029 *.sh
      - run: npm install yarn
      - run: yarn install
      - run: npx eslint .
